package com.zhou.wise.pojo;

import java.io.Serializable;
import java.util.Date;

public class DeviceManage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_manage.h_id
     *
     * @mbggenerated
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_manage.h_vender
     *
     * @mbggenerated
     */
    private String hVender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_manage.h_model
     *
     * @mbggenerated
     */
    private String hModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_manage.h_sign_status
     *
     * @mbggenerated
     */
    private Integer hSignStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_manage.h_CREATETIME
     *
     * @mbggenerated
     */
    private Date hCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_manage.h_id
     *
     * @return the value of device_manage.h_id
     *
     * @mbggenerated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_manage.h_id
     *
     * @param hId the value for device_manage.h_id
     *
     * @mbggenerated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_manage.h_vender
     *
     * @return the value of device_manage.h_vender
     *
     * @mbggenerated
     */
    public String gethVender() {
        return hVender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_manage.h_vender
     *
     * @param hVender the value for device_manage.h_vender
     *
     * @mbggenerated
     */
    public void sethVender(String hVender) {
        this.hVender = hVender == null ? null : hVender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_manage.h_model
     *
     * @return the value of device_manage.h_model
     *
     * @mbggenerated
     */
    public String gethModel() {
        return hModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_manage.h_model
     *
     * @param hModel the value for device_manage.h_model
     *
     * @mbggenerated
     */
    public void sethModel(String hModel) {
        this.hModel = hModel == null ? null : hModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_manage.h_sign_status
     *
     * @return the value of device_manage.h_sign_status
     *
     * @mbggenerated
     */
    public Integer gethSignStatus() {
        return hSignStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_manage.h_sign_status
     *
     * @param hSignStatus the value for device_manage.h_sign_status
     *
     * @mbggenerated
     */
    public void sethSignStatus(Integer hSignStatus) {
        this.hSignStatus = hSignStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_manage.h_CREATETIME
     *
     * @return the value of device_manage.h_CREATETIME
     *
     * @mbggenerated
     */
    public Date gethCreatetime() {
        return hCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_manage.h_CREATETIME
     *
     * @param hCreatetime the value for device_manage.h_CREATETIME
     *
     * @mbggenerated
     */
    public void sethCreatetime(Date hCreatetime) {
        this.hCreatetime = hCreatetime;
    }
}