package com.zhou.wise.pojo;

import java.util.Date;

public class RequestLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.user_login_id
     *
     * @mbggenerated
     */
    private String userLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.acction_name
     *
     * @mbggenerated
     */
    private String acctionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.request
     *
     * @mbggenerated
     */
    private String request;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.response
     *
     * @mbggenerated
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.client_ip
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.server_ip
     *
     * @mbggenerated
     */
    private String serverIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.system
     *
     * @mbggenerated
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request_log.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.id
     *
     * @return the value of request_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.id
     *
     * @param id the value for request_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.user_name
     *
     * @return the value of request_log.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.user_name
     *
     * @param userName the value for request_log.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.user_phone
     *
     * @return the value of request_log.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.user_phone
     *
     * @param userPhone the value for request_log.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.user_login_id
     *
     * @return the value of request_log.user_login_id
     *
     * @mbggenerated
     */
    public String getUserLoginId() {
        return userLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.user_login_id
     *
     * @param userLoginId the value for request_log.user_login_id
     *
     * @mbggenerated
     */
    public void setUserLoginId(String userLoginId) {
        this.userLoginId = userLoginId == null ? null : userLoginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.user_type
     *
     * @return the value of request_log.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.user_type
     *
     * @param userType the value for request_log.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.acction_name
     *
     * @return the value of request_log.acction_name
     *
     * @mbggenerated
     */
    public String getAcctionName() {
        return acctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.acction_name
     *
     * @param acctionName the value for request_log.acction_name
     *
     * @mbggenerated
     */
    public void setAcctionName(String acctionName) {
        this.acctionName = acctionName == null ? null : acctionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.class_name
     *
     * @return the value of request_log.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.class_name
     *
     * @param className the value for request_log.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.method_name
     *
     * @return the value of request_log.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.method_name
     *
     * @param methodName the value for request_log.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.url
     *
     * @return the value of request_log.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.url
     *
     * @param url the value for request_log.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.request
     *
     * @return the value of request_log.request
     *
     * @mbggenerated
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.request
     *
     * @param request the value for request_log.request
     *
     * @mbggenerated
     */
    public void setRequest(String request) {
        this.request = request == null ? null : request.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.response
     *
     * @return the value of request_log.response
     *
     * @mbggenerated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.response
     *
     * @param response the value for request_log.response
     *
     * @mbggenerated
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.client_ip
     *
     * @return the value of request_log.client_ip
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.client_ip
     *
     * @param clientIp the value for request_log.client_ip
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.server_ip
     *
     * @return the value of request_log.server_ip
     *
     * @mbggenerated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.server_ip
     *
     * @param serverIp the value for request_log.server_ip
     *
     * @mbggenerated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.version
     *
     * @return the value of request_log.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.version
     *
     * @param version the value for request_log.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.system
     *
     * @return the value of request_log.system
     *
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.system
     *
     * @param system the value for request_log.system
     *
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.model
     *
     * @return the value of request_log.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.model
     *
     * @param model the value for request_log.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.state
     *
     * @return the value of request_log.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.state
     *
     * @param state the value for request_log.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.createtime
     *
     * @return the value of request_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.createtime
     *
     * @param createtime the value for request_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request_log.updatetime
     *
     * @return the value of request_log.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request_log.updatetime
     *
     * @param updatetime the value for request_log.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}